stages:
  preprocess_data:
    cmd: python ../steps/clean_data.py --config=params.yaml
    deps:
      - ../steps/read_config_params.py
      - ../steps/get_data.py
      - ../steps/clean_data.py
      - ../src/label_encoder.py
      - ../src/one_hot_encoder.py
      - ../data/raw/salary_dataset.csv
    outs:
      - ../data/interim/salary_dataset.csv
      - ../encoder/OneHotEncoder.joblib
      - ../encoder/Education_Level_LabelEncoder.joblib
      - ../encoder/Job_Title_LabelEncoder.joblib
      - ../encoder/label_map.json

  split_data:
    cmd: python ../steps/split_data.py --config=params.yaml
    deps:
      - ../steps/split_data.py
      - ../steps/read_config_params.py
      - ../steps/get_data.py
      - ../data/interim/salary_dataset.csv
    outs:
      - ../data/processed/train_salary_dataset.csv
      - ../data/processed/test_salary_dataset.csv

  train_and_evaluate:
    cmd: python ../steps/train_model.py --config=params.yaml
    deps:
      - ../steps/train_model.py
      - data/processed/train_salary_dataset.csv
      - data/processed/test_salary_dataset.csv
    params:
      - estimators.RandomForestRegressor.params.n_estimators
    metrics:
      - reports/scores.json:
          cache: false
      - reports/params.json:
          cache: false
    outs:
      - models/model.joblib