base:
  project: salary-prediction-project
  random_state: 30
  target_col: Salary

data_source:
  data_source_path: data/raw/salary_dataset.csv

ingest_data:
  interim_dataset_csv: data/interim/salary_dataset.csv