base:
  project: salary-prediction-project
  random_state: 30
  target_col: 5

data_source:
  data_source_path: data/raw/salary_dataset.csv

preprocess_data_source:
  interim_dataset_csv: data/interim/salary_dataset.csv
  dataset_schema_json: schema
  encoder_path: encoder

processed_data_source:
  train_data_path: data/processed/train_salary_dataset.csv
  test_data_path: data/processed/test_salary_dataset.csv
  test_size: 0.2

estimators:
  RandomForestRegressor:
    params:
      n_estimators: 10

model:
  model_name: RandomForestRegression
  model_dir: models
  model_path: models/model.joblib

reports:
  params: reports/params.json
  scores: reports/scores.json