base:
  project: salary-prediction-project
  random_state: 30
  target_col: Salary

data_source:
  data_source_path: data/raw/salary_dataset.csv

preprocess_data_source:
  interim_dataset_csv: data/interim/salary_dataset.csv

processed_data_source:
  train_data_path: data/processed/train_salary_dataset.csv
  test_data_path: data/processed/test_salary_dataset.csv
  test_size: 0.2